version: "3"

services:
  rails-init:
    image: rails:init
    build:
      context: .
      dockerfile: rails-init.Dockerfile
    command: rails new railsapp
#    command: bash
#    command: tail -f /dev/null
    volumes:
      - ./rails:/home/developer/app/railsapp

  rails-dev:
    image: rails:dev
    build:
      context: .
      dockerfile: rails-dev.Dockerfile
    command: bundle exec rails server -b 0.0.0.0
    volumes:
      - ./rails:/home/developer/app/railsapp
    ports:
      - 3000:3000
